{% set name = "gazpacho" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gazpacho-{{ version }}.tar.gz
  sha256: 1579c1be2de05b5ded0a97107b179d12491392fb095aeab185b283ea48cd7010

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=38.6.0
  run:
    - python >={{ python_min }}

test:
  imports:
    - gazpacho
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gazpacho.xyz/
  dev_url: https://github.com/maxhumber/gazpacho
  summary: The simple, fast, and modern web scraping library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
